name: Run Node.js script on push or repository_dispatch

on:
  repository_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Run script
        run: TARGET_DIR=feeds npm start
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Feeds
          branch: gh-pages
          file_pattern: "feeds/*.xml"
          commit_user_name: github-tgspace-collector-actions[bot]
          commit_user_email: jmas.ukraine+tgspace-collector@gmail.com
          commit_author: Oleksandr Maslakov <tgspace-collector@gmail.com>
